[features]
seeds = false
skip-lint = false

[programs.devnet]
delta_neutral_adaptor = "DNAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.mainnet-beta]
delta_neutral_adaptor = "DNAxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.validator.clone]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"

[[test.validator.clone]]
address = "vVoLTRjQmtFpiYoegx285Ze4gsLJ8ZxgFKVcuvmG1a8"
