/**
 * OrderExecutor — idempotent, retry-aware perp order execution for QuantVault.
 *
 * Design:
 *   - Each order carries a caller-generated UUID. Calling placeOrder() twice
 *     with the same id is a no-op after the first successful submission.
 *   - Orders move through the lifecycle:
 *       pending → submitted → filled | failed
 *   - Internally delegates to DriftManager for the actual on-chain calls so
 *     that all Drift interaction remains in one place.
 */

import { v4 as uuidv4 } from "uuid";
import logger from "./logger";
import { DriftManager } from "./drift";

// ── Types ─────────────────────────────────────────────────────────────────────

export interface PendingOrder {
  /** Caller-supplied UUID — used for idempotency checks. */
  id: string;
  marketIndex: number;
  direction: "long" | "short";
  /** Notional size in USD. */
  sizeUsd: number;
  status: "pending" | "submitted" | "filled" | "failed";
  txSignature?: string;
  attempts: number;
  /** ISO timestamp of the last attempt. */
  lastAttemptAt?: string;
  /** Reason for the last failure, if any. */
  lastError?: string;
}

// ── Constants ─────────────────────────────────────────────────────────────────

const MAX_PLACE_ATTEMPTS = 3;
const RETRY_DELAY_MS = 1_000;

// ── Helpers ───────────────────────────────────────────────────────────────────

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ── OrderExecutor ─────────────────────────────────────────────────────────────

export class OrderExecutor {
  /** In-memory order store: orderId → PendingOrder */
  private readonly orders = new Map<string, PendingOrder>();

  constructor(private readonly drift: DriftManager) {}

  // ── Public API ─────────────────────────────────────────────────────────────

  /**
   * Place a new perp order on Drift.
   *
   * Idempotency: if an order with `order.id` has already been submitted or
   * filled, this method returns immediately with the existing tx signature
   * (or an empty string if the previous attempt failed).
   *
   * @param order       Order descriptor. `id` must be a UUID generated by the caller.
   * @param oraclePrice Current oracle price used to size the position.
   * @returns           Confirmed transaction signature, or empty string on terminal failure.
   */
  async placeOrder(order: PendingOrder, oraclePrice: number): Promise<string> {
    // ── Idempotency guard ──────────────────────────────────────────────────
    const existing = this.orders.get(order.id);
    if (existing) {
      if (existing.status === "submitted" || existing.status === "filled") {
        logger.info(
          `OrderExecutor.placeOrder: order ${order.id} already ${existing.status} ` +
          `(tx: ${existing.txSignature ?? "N/A"}), skipping`
        );
        return existing.txSignature ?? "";
      }
      if (existing.status === "failed" && existing.attempts >= MAX_PLACE_ATTEMPTS) {
        logger.warn(
          `OrderExecutor.placeOrder: order ${order.id} has permanently failed ` +
          `after ${existing.attempts} attempts`
        );
        return "";
      }
      // Allow retry of a failed order that hasn't exhausted attempts
      logger.info(
        `OrderExecutor.placeOrder: retrying order ${order.id} ` +
        `(previous status: ${existing.status}, attempts: ${existing.attempts})`
      );
    }

    // Upsert the order record into our map
    const record: PendingOrder = existing
      ? { ...existing, status: "pending" }
      : { ...order, status: "pending", attempts: 0 };

    this.orders.set(order.id, record);

    // ── Placement loop ─────────────────────────────────────────────────────
    for (let attempt = 1; attempt <= MAX_PLACE_ATTEMPTS; attempt++) {
      record.attempts = attempt;
      record.lastAttemptAt = new Date().toISOString();

      logger.info(
        `OrderExecutor: placing ${record.direction} ${record.marketIndex} ` +
        `$${record.sizeUsd.toFixed(2)} — attempt ${attempt}/${MAX_PLACE_ATTEMPTS} ` +
        `(id: ${record.id})`
      );

      try {
        let txSig: string;

        if (record.direction === "short") {
          txSig = await this.drift.openShortPerp(
            record.marketIndex,
            record.sizeUsd,
            oraclePrice
          );
        } else {
          // Long perp — close an existing short or open a long.
          // For the delta-neutral strategy "long" means closing a short.
          txSig = await this.drift.closePosition(record.marketIndex, oraclePrice);
        }

        record.status = "submitted";
        record.txSignature = txSig;
        record.lastError = undefined;

        logger.info(
          `OrderExecutor: order ${record.id} submitted — tx: ${txSig}`
        );

        this.orders.set(record.id, { ...record });
        return txSig;
      } catch (err) {
        const msg = err instanceof Error ? err.message : String(err);
        record.lastError = msg;

        logger.warn(
          `OrderExecutor: order ${record.id} attempt ${attempt} failed: ${msg}`
        );

        if (attempt < MAX_PLACE_ATTEMPTS) {
          const delay = RETRY_DELAY_MS * attempt;
          logger.info(`OrderExecutor: retrying in ${delay}ms...`);
          await sleep(delay);
        }
      }
    }

    // All attempts exhausted
    record.status = "failed";
    this.orders.set(record.id, { ...record });

    logger.error(
      `OrderExecutor: order ${record.id} permanently failed after ` +
      `${MAX_PLACE_ATTEMPTS} attempts. Last error: ${record.lastError}`
    );

    return "";
  }

  /**
   * Cancel all open orders for a given perp market index.
   *
   * Delegates to DriftClient.cancelOrders which cancels all open limit/market
   * orders for the market. Any locally-tracked orders for this market that
   * are still "submitted" are moved to "failed".
   */
  async cancelMarketOrders(marketIndex: number): Promise<void> {
    logger.info(`OrderExecutor: cancelling all orders for market ${marketIndex}`);

    try {
      // DriftManager does not expose cancelOrders directly — call through the
      // underlying driftClient via the public accessor if available, or log a
      // clear message so the caller knows to handle it.
      const driftClient = (this.drift as any).driftClient;
      if (driftClient && typeof driftClient.cancelOrders === "function") {
        await driftClient.cancelOrders(marketIndex);
        logger.info(`OrderExecutor: cancelled orders for market ${marketIndex}`);
      } else {
        logger.warn(
          `OrderExecutor: driftClient.cancelOrders not accessible — ` +
          `please cancel market ${marketIndex} orders manually`
        );
      }
    } catch (err) {
      logger.error(
        `OrderExecutor: failed to cancel orders for market ${marketIndex}: ${err}`
      );
      throw err;
    }

    // Mark any locally-tracked submitted orders for this market as failed
    for (const [id, order] of this.orders.entries()) {
      if (order.marketIndex === marketIndex && order.status === "submitted") {
        this.orders.set(id, {
          ...order,
          status: "failed",
          lastError: "cancelled by OrderExecutor.cancelMarketOrders",
          lastAttemptAt: new Date().toISOString(),
        });
        logger.info(`OrderExecutor: marked order ${id} as failed (cancelled)`);
      }
    }
  }

  /**
   * Return a snapshot of all currently tracked orders.
   */
  getPendingOrders(): PendingOrder[] {
    return Array.from(this.orders.values());
  }

  /**
   * Mark an order as filled (called externally once fill is confirmed on-chain).
   */
  markFilled(orderId: string): void {
    const order = this.orders.get(orderId);
    if (!order) {
      logger.warn(`OrderExecutor.markFilled: unknown order id ${orderId}`);
      return;
    }
    this.orders.set(orderId, { ...order, status: "filled" });
    logger.info(`OrderExecutor: order ${orderId} marked as filled`);
  }

  /**
   * Purge orders that have reached a terminal state (filled or permanently
   * failed). Call periodically to prevent unbounded memory growth.
   */
  pruneTerminalOrders(): void {
    let pruned = 0;
    for (const [id, order] of this.orders.entries()) {
      if (order.status === "filled" || order.status === "failed") {
        this.orders.delete(id);
        pruned++;
      }
    }
    if (pruned > 0) {
      logger.debug(`OrderExecutor: pruned ${pruned} terminal orders`);
    }
  }

  /**
   * Generate a new random UUID suitable for use as an order id.
   * Convenience helper so callers don't need to import uuid directly.
   */
  static newOrderId(): string {
    return uuidv4();
  }
}
